### ISSUE TITLE
Duplicate list

### ISSUE THREAD

**Issue by amorriscode** [Tom2718/Awesome-Ethereum#5]
There [are](https://github.com/btomashvili/awesome-ethereum) [a](https://github.com/vinsgo/awesome-ethereum) [couple](https://github.com/void4/awesome-ethereum) [other](https://github.com/toadkicker/awesome-ethereum) `awesome-ethereum` lists. Perhaps you could connect with them to compile one master list _or_ race to see who will be there first person to be added to the [curated list of awesome lists](https://github.com/sindresorhus/awesome).

**Comment by Tom2718** [comment]
Some of the other lists haven't been updated in a long time and contain outdated resources. Also, I think we diverge on a philosophical point: I don't want to have a list of tokens or DApps built on Ethereum because I don't think it's useful and it incites exploitation by pushing your own project for publicity. I'm quite happy to have a link to [State of the DApps](https://www.stateofthedapps.com/) for example, which accomplishes the same goal. Furthermore, I want to keep this list as up to date as possible, removing tutorials or other links if the content becomes deprecated.

So I guess it's a race to [awesome](https://github.com/sindresorhus/awesome).
